title: Malware analysis database
author: demon-i386
avatar: "./root/assets/logo.jpg"
rss-description: Open malware analysis / reversing database

twitter:
  username: demon-i386
defaults:
  - scope:
      path: ""
    values:
      image:
        path: ./root/assets/logo.jpg
        height: 600
        width: 600
